apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: lvm-operator
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - openshift-storage