apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-configs
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: cluster/lvm-kustomize
    repoURL: https://github.com/cdwertmann/test
    targetRevision: HEAD
  syncPolicy:
    automated: {}
