apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator-subscription
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  channel: stable-3.9
  installPlanApproval: Automatic
  name: quay-operator
